<?php

namespace SplitTestForElementor\Classes\Misc;

class Errors {

	public static $MAXIMUM_TEST_COUNT_REACHED = "MAXIMUM_TEST_COUNT_REACHED";
	public static $MAXIMUM_VARIATION_COUNT_REACHED = "MAXIMUM_VARIATION_COUNT_REACHED";
	public static $CONVERSION_TYPE_MISSING = "CONVERSION_TYPE_MISSING";
	public static $CONVERSION_PAGE_MISSING = "CONVERSION_PAGE_MISSING";
	public static $CONVERSION_URL_MISSING = "CONVERSION_URL_MISSING";
	public static $MISSING_RIGHTS = "MISSING_RIGHTS";

	/* Conversion Tracking */
	public static $MISSING_OR_EMPTY_TEST_ID = "MISSING_OR_EMPTY_TEST_ID";
	public static $MISSING_OR_EMPTY_VARIATION_ID = "MISSING_OR_EMPTY_VARIATION_ID";

}